### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by Akendo** [svartalf/rust-icmp#4]
Running the test is failing currently:
```rust
akendo@t480 ~/s/rust-icmp> cargo test                                                                                                                                                 [11/1927]
   Compiling libc v0.2.51
   Compiling icmp v0.2.0 (/home/akendo/src/rust-icmp)
    Finished dev [unoptimized + debuginfo] target(s) in 2.25s
     Running target/debug/deps/icmp-3d2b3c254eeb2884

running 10 tests
test tests::broadcast_v4 ... FAILED
test tests::qos_v4 ... FAILED
test tests::broadcast_v6 ... FAILED
test tests::qos_v6 ... FAILED
test tests::read_timeout_v6 ... FAILED
test tests::ttl_v4 ... FAILED
test tests::read_timeout_v4 ... FAILED
test tests::ttl_v6 ... FAILED
test tests::write_timeout_v4 ... FAILED
test tests::write_timeout_v6 ... FAILED

failures:

---- tests::broadcast_v4 stdout ----
thread 'tests::broadcast_v4' panicked at 'received error for `IcmpSocket::connect(ipv4())`: Operation not permitted (os error 1)', src/tests.rs:114:18
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
                             
---- tests::qos_v4 stdout ----        
thread 'tests::qos_v4' panicked at 'received error for `IcmpSocket::connect(ipv4())`: Operation not permitted (os error 1)', src/tests.rs:48:18
                                       
---- tests::broadcast_v6 stdout ----   
thread 'tests::broadcast_v6' panicked at 'received error for `IcmpSocket::connect(ipv6())`: Operation not permitted (os error 1)', src/tests.rs:128:18
         
---- tests::qos_v6 stdout ----
thread 'tests::qos_v6' panicked at 'received error for `IcmpSocket::connect(ipv6())`: Operation not permitted (os error 1)', src/tests.rs:58:18
                                                                                                                                                      
---- tests::read_timeout_v6 stdout ----                                       
thread 'tests::read_timeout_v6' panicked at 'received error for `IcmpSocket::connect(ipv6())`: Operation not permitted (os error 1)', src/tests.rs:79:18
                              
---- tests::ttl_v4 stdout ----                                                                                                                 
thread 'tests::ttl_v4' panicked at 'received error for `IcmpSocket::connect(ipv4())`: Operation not permitted (os error 1)', src/tests.rs:28:18
                                    
---- tests::read_timeout_v4 stdout ----                                                                                                               
thread 'tests::read_timeout_v4' panicked at 'received error for `IcmpSocket::connect(ipv4())`: Operation not permitted (os error 1)', src/tests.rs:67:18
                              
---- tests::ttl_v6 stdout ----                                                                                                                 
thread 'tests::ttl_v6' panicked at 'received error for `IcmpSocket::connect(ipv6())`: Operation not permitted (os error 1)', src/tests.rs:38:18
                                       
---- tests::write_timeout_v4 stdout ----                                                                                                                
thread 'tests::write_timeout_v4' panicked at 'received error for `IcmpSocket::connect(ipv4())`: Operation not permitted (os error 1)', src/tests.rs:91:18
                              
---- tests::write_timeout_v6 stdout ----                                                                                                       
thread 'tests::write_timeout_v6' panicked at 'received error for `IcmpSocket::connect(ipv6())`: Operation not permitted (os error 1)', src/tests.rs:103:18
                                       
                                                                                                                                                        
failures:
    tests::broadcast_v4       
    tests::broadcast_v6                                                                                                                        
    tests::qos_v4
    tests::qos_v6                       
    tests::read_timeout_v4                                                                                                                               
    tests::read_timeout_v6
    tests::ttl_v4                       
    tests::ttl_v6                                                                                                                                         
    tests::write_timeout_v4
    tests::write_timeout_v6
         
test result: FAILED. 0 passed; 10 failed; 0 ignored; 0 measured; 0 filtered out
                       
error: test failed, to rerun pass '--lib'
```

**Comment by Akendo** [comment]
Just like #1 it is necessary to run the `sudo setcap cap_net_raw+ep  target/debug/icmp-3d2b3c254eeb2884` command.
